dbToUITableNameReplace = {
    'aluminum_electrolytic_capacitors': 'Aluminum Electrolytic Capacitors',
    'bjts': 'BJTs',
    'ceramic_capacitors': 'Ceramic Capacitors',
    'chip_resistors': 'Chip Resistors',
    'comparators': 'Comparators',
    'dacs': 'DACs',
    'encoders': 'Encoders',
    'ferrite_beads': 'Ferrite Beads',
    'ffc_fpc_connectors': 'FFC_FPC Connectors',
    'header_connectors': 'Header Connectors',
    'inductors': 'Inductors',
    'led_drivers': 'LED Drivers',
    'leds': 'LEDs',
    'linear_voltage_regulators': 'Linear Voltage Regulators',
    'mosfets': 'MOSFETs',
    'schottky_diodes': 'Schottky Diodes',
    'slide_switches': 'Slide Switches',
    'socs': 'SoCs',
    'spring_connectors': 'Spring Connectors',
    'tvs_diodes': 'TVS Diodes',
    'wire_to_board_connectors': 'Wire to Board Connectors',
    'zener_diodes': 'Zener Diodes',

}

dbToUIColumnNameReplace = {
    'ID': 'Id',
    'BoxName': 'Box Name',
    'ManufacturerPartNumber': 'Manufacturer Part Number',
    'LastUpdated': 'Last Updated',
    'TemperatureCoefficient': 'Temperature Coefficient',
}

digiToDbTableNameReplace = {
    'Aluminum Electrolytic Capacitors': 'aluminum_electrolytic_capacitors',
    'Transistors - Bipolar (BJT) - Single': 'bjts',
    'Ceramic Capacitors': 'ceramic_capacitors',
    'Chip Resistor - Surface Mount': 'chip_resistors',
    'Linear - Comparators': 'comparators',
    'Data Acquisition - Digital to Analog Converters (DAC)': 'dacs',
    'Encoders': 'encoders',
    'Ferrite Beads': 'ferrite_beads',
    'FFC_FPC Connectors': 'ffc_fpc_connectors',
    'Header Connectors': 'header_connectors',
    'Inductors': 'inductors',
    'LED Drivers': 'led_drivers',
    'LEDs': 'leds',
    'Linear Voltage Regulators': 'linear_voltage_regulators',
    'MOSFETs': 'mosfets',
    'Schottky Diodes': 'schottky_diodes',
    'Slide Switches': 'slide_switches',
    'SoCs': 'socs',
    'Spring Connectors': 'spring_connectors',
    'TVS Diodes': 'tvs_diodes',
    'Wire to Board Connectors': 'wire_to_board_connectors',
    'Zener Diodes': 'zener_diodes',
}